import { createClient } from "https://esm.sh/@supabase/supabase-js@2";
import { SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY } from "./config.js";

const configured = !SUPABASE_URL.includes("PASTE_") && !SUPABASE_PUBLISHABLE_KEY.includes("PASTE_");
const sb = configured ? createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY) : null;
const $ = s => document.querySelector(s), $$ = s => [...document.querySelectorAll(s)];
const E = {login:$("#login"),app:$("#app"),loginForm:$("#loginForm"),email:$("#email"),loginMsg:$("#loginMsg"),signOut:$("#signOut"),events:$("#events"),empty:$("#empty"),needsBanner:$("#needsBanner"),needsText:$("#needsText"),viewTitle:$("#viewTitle"),viewHelp:$("#viewHelp"),addBtn:$("#addBtn"),mobileAdd:$("#mobileAdd"),eventDialog:$("#eventDialog"),eventForm:$("#eventForm"),eventHeading:$("#eventHeading"),eventId:$("#eventId"),person:$("#person"),title:$("#title"),date:$("#date"),time:$("#time"),location:$("#location"),notes:$("#notes"),deleteBtn:$("#deleteBtn"),detailDialog:$("#detailDialog"),detailPerson:$("#detailPerson"),detailTitle:$("#detailTitle"),detailBody:$("#detailBody"),driverBox:$("#driverBox"),editBtn:$("#editBtn"),calendarBtn:$("#calendarBtn"),nameDialog:$("#nameDialog"),nameForm:$("#nameForm"),displayName:$("#displayName"),toast:$("#toast")};
let user=null, profile=null, rows=[], view="upcoming", detail=null, channel=null;
const esc=(v="")=>String(v).replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[m]));
const dt=e=>new Date(`${e.event_date}T${e.event_time||"00:00"}`), past=e=>dt(e)<new Date();
const fDate=d=>new Intl.DateTimeFormat(undefined,{weekday:"short",month:"short",day:"numeric"}).format(new Date(`${d}T12:00:00`));
const fTime=t=>{const [h,m]=(t||"00:00").split(":").map(Number);return new Intl.DateTimeFormat(undefined,{hour:"numeric",minute:"2-digit"}).format(new Date(2000,0,1,h,m))};
function toast(s){E.toast.textContent=s;E.toast.hidden=false;clearTimeout(toast.t);toast.t=setTimeout(()=>E.toast.hidden=true,2400)}
function setView(v){view=v;$$('[data-view]').forEach(b=>b.classList.toggle('active',b.dataset.view===v));const meta={upcoming:["Upcoming","Appointments and errands for Mimi and Grandaddy."],needs:["Needs Driver","Upcoming events that still need transportation."],mine:["My Rides","Transportation you have signed up to provide."],all:["All Events","Upcoming and past events."]};[E.viewTitle.textContent,E.viewHelp.textContent]=meta[v];render()}
function filtered(){const a=[...rows].sort((a,b)=>dt(a)-dt(b));if(view==='upcoming')return a.filter(e=>!past(e));if(view==='needs')return a.filter(e=>!past(e)&&!e.driver_user_id);if(view==='mine')return a.filter(e=>!past(e)&&e.driver_user_id===user?.id);return a}
function card(e){const cls=e.person==='Grandaddy'?'grandaddy':'';const status=e.driver_user_id?`<span class="covered">● ${esc(e.driver_name||'Ride covered')} is driving</span>`:`<span class="needed-text">DRIVER NEEDED</span>`;const claim=!e.driver_user_id&&!past(e)?`<button data-claim="${e.id}">I can drive</button>`:'';return `<article class="card ${cls}"><div class="top"><span class="person">${esc(e.person)}</span><span class="when">${fDate(e.event_date)} · ${fTime(e.event_time)}</span></div><h3>${esc(e.title)}</h3>${e.location?`<div class="location">${esc(e.location)}</div>`:''}<div class="ride">${status}<div class="card-actions">${claim}<button class="secondary" data-open="${e.id}">Details</button></div></div></article>`}
function render(){const needs=rows.filter(e=>!past(e)&&!e.driver_user_id);E.needsBanner.hidden=!needs.length;E.needsText.textContent=`${needs.length} ${needs.length===1?'ride needs':'rides need'} drivers`;const a=filtered();E.empty.hidden=!!a.length;E.events.innerHTML=a.map(card).join('');$$('[data-open]').forEach(b=>b.onclick=()=>openDetail(b.dataset.open));$$('[data-claim]').forEach(b=>b.onclick=()=>claim(b.dataset.claim))}
async function load(){const {data,error}=await sb.from('events').select('*').order('event_date').order('event_time');if(error)return toast(error.message);rows=data||[];render()}
async function session(s){if(!s){user=profile=null;rows=[];E.app.hidden=true;E.login.hidden=false;if(channel){await sb.removeChannel(channel);channel=null}return}user=s.user;const {data,error}=await sb.from('family_members').select('email,display_name').eq('email',user.email.toLowerCase()).maybeSingle();if(error||!data){await sb.auth.signOut();E.loginMsg.textContent='This email is not on the family access list.';return}profile=data;E.login.hidden=true;E.app.hidden=false;if(!profile.display_name)E.nameDialog.showModal();await load();if(!channel)channel=sb.channel('events').on('postgres_changes',{event:'*',schema:'public',table:'events'},()=>load()).subscribe()}
async function init(){if(!configured){E.loginMsg.textContent='Setup required: add your Supabase URL and publishable key to config.js.';return}const {data}=await sb.auth.getSession();await session(data.session);sb.auth.onAuthStateChange((_e,s)=>session(s));$$('[data-view]').forEach(b=>b.onclick=()=>setView(b.dataset.view));E.needsBanner.onclick=()=>setView('needs')}
E.loginForm.onsubmit=async e=>{e.preventDefault();const email=E.email.value.trim().toLowerCase();E.loginMsg.textContent='Checking access…';const {error}=await sb.auth.signInWithOtp({email,options:{emailRedirectTo:location.href,shouldCreateUser:true}});E.loginMsg.textContent=error?error.message:'Check your email and tap the sign-in link.'};
E.signOut.onclick=()=>sb.auth.signOut();
function newEvent(){E.eventForm.reset();E.eventHeading.textContent='Add Event';E.eventId.value='';E.person.value='Mimi';E.date.value=new Date().toISOString().slice(0,10);E.deleteBtn.hidden=true;E.eventDialog.showModal()}
E.addBtn.onclick=newEvent;E.mobileAdd.onclick=newEvent;$("#closeEvent").onclick=()=>E.eventDialog.close();$("#cancelEvent").onclick=()=>E.eventDialog.close();
E.eventForm.onsubmit=async e=>{e.preventDefault();const p={person:E.person.value,title:E.title.value.trim(),event_date:E.date.value,event_time:E.time.value,location:E.location.value.trim()||null,notes:E.notes.value.trim()||null,updated_at:new Date().toISOString()};const r=E.eventId.value?await sb.from('events').update(p).eq('id',E.eventId.value):await sb.from('events').insert({...p,created_by:user.id});if(r.error)return toast(r.error.message);E.eventDialog.close();toast('Saved.');await load()};
async function claim(id){if(!profile?.display_name){E.nameDialog.showModal();return}const {data,error}=await sb.from('events').update({driver_user_id:user.id,driver_name:profile.display_name,updated_at:new Date().toISOString()}).eq('id',id).is('driver_user_id',null).select().maybeSingle();if(error)return toast(error.message);if(!data)return toast('Someone else just claimed this ride.');E.detailDialog.close();toast('Thank you!');await load()}
async function unclaim(id){const {error}=await sb.from('events').update({driver_user_id:null,driver_name:null,updated_at:new Date().toISOString()}).eq('id',id).eq('driver_user_id',user.id);if(error)return toast(error.message);E.detailDialog.close();toast('Ride released.');await load()}
function openDetail(id){detail=rows.find(e=>e.id===id);if(!detail)return;E.detailPerson.textContent=detail.person;E.detailTitle.textContent=detail.title;E.detailBody.innerHTML=`<div class="detail-line"><span>📅</span><span>${fDate(detail.event_date)}</span></div><div class="detail-line"><span>🕐</span><span>${fTime(detail.event_time)}</span></div>${detail.location?`<div class="detail-line"><span>📍</span><span>${esc(detail.location)}</span></div>`:''}${detail.notes?`<div class="detail-line"><span>📝</span><span>${esc(detail.notes)}</span></div>`:''}`;if(detail.driver_user_id){const mine=detail.driver_user_id===user.id;E.driverBox.innerHTML=`<strong class="covered">✓ ${esc(detail.driver_name||'Someone')} is driving</strong>${mine?'<button id="unclaim" class="secondary">I can\'t drive anymore</button>':''}`;if(mine)$("#unclaim").onclick=()=>unclaim(detail.id)}else{E.driverBox.innerHTML=`<strong class="needed-text">DRIVER NEEDED</strong>${!past(detail)?'<button id="claimDetail">I can drive</button>':''}`;if(!past(detail))$("#claimDetail").onclick=()=>claim(detail.id)}E.detailDialog.showModal()}
$("#closeDetail").onclick=()=>E.detailDialog.close();
E.editBtn.onclick=()=>{if(!detail)return;E.detailDialog.close();E.eventHeading.textContent='Edit Event';E.eventId.value=detail.id;E.person.value=detail.person;E.title.value=detail.title;E.date.value=detail.event_date;E.time.value=(detail.event_time||'').slice(0,5);E.location.value=detail.location||'';E.notes.value=detail.notes||'';E.deleteBtn.hidden=false;E.eventDialog.showModal()};
E.deleteBtn.onclick=async()=>{if(!E.eventId.value||!confirm('Delete this event?'))return;const {error}=await sb.from('events').delete().eq('id',E.eventId.value);if(error)return toast(error.message);E.eventDialog.close();toast('Deleted.');await load()};
E.nameForm.onsubmit=async e=>{e.preventDefault();const name=E.displayName.value.trim();const {error}=await sb.from('family_members').update({display_name:name}).eq('email',user.email.toLowerCase());if(error)return toast(error.message);profile.display_name=name;E.nameDialog.close();toast('Saved.')};
E.calendarBtn.onclick=()=>{if(!detail)return;const start=`${detail.event_date.replaceAll('-','')}T${(detail.event_time||'00:00').replace(':','')}00`;const endDate=new Date(dt(detail).getTime()+3600000),pad=n=>String(n).padStart(2,'0');const end=`${endDate.getFullYear()}${pad(endDate.getMonth()+1)}${pad(endDate.getDate())}T${pad(endDate.getHours())}${pad(endDate.getMinutes())}00`;const body=['BEGIN:VCALENDAR','VERSION:2.0','PRODID:-//Family Transportation//EN','BEGIN:VEVENT',`DTSTART:${start}`,`DTEND:${end}`,`SUMMARY:${detail.person}: ${detail.title}`,`LOCATION:${detail.location||''}`,`DESCRIPTION:${(detail.notes||'').replace(/\n/g,'\\n')}`,'END:VEVENT','END:VCALENDAR'].join('\r\n');const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([body],{type:'text/calendar'}));a.download=`${detail.person}-${detail.event_date}.ics`;a.click();URL.revokeObjectURL(a.href)};
init();
