import { createClient } from "https://esm.sh/@supabase/supabase-js@2";
import { SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY } from "./config.js";
const sb=createClient(SUPABASE_URL,SUPABASE_PUBLISHABLE_KEY),$=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const els={login:$("#login"),app:$("#app"),loginForm:$("#loginForm"),email:$("#email"),loginMsg:$("#loginMsg"),codeForm:$("#codeForm"),otpCode:$("#otpCode"),changeEmailBtn:$("#changeEmailBtn"),signOut:$("#signOut"),needsBanner:$("#needsBanner"),needsText:$("#needsText"),addBtn:$("#addBtn"),mobileAdd:$("#mobileAdd"),viewTitle:$("#viewTitle"),viewHelp:$("#viewHelp"),events:$("#events"),empty:$("#empty"),eventDialog:$("#eventDialog"),eventForm:$("#eventForm"),eventHeading:$("#eventHeading"),eventId:$("#eventId"),person:$("#person"),title:$("#title"),date:$("#date"),time:$("#time"),pickupTime:$("#pickupTime"),location:$("#location"),notes:$("#notes"),deleteBtn:$("#deleteBtn"),closeEvent:$("#closeEvent"),cancelEvent:$("#cancelEvent"),detailDialog:$("#detailDialog"),detailPerson:$("#detailPerson"),detailTitle:$("#detailTitle"),detailBody:$("#detailBody"),driverBox:$("#driverBox"),closeDetail:$("#closeDetail"),calendarBtn:$("#calendarBtn"),editBtn:$("#editBtn"),agencyDialog:$("#agencyDialog"),agencyForm:$("#agencyForm"),agencyName:$("#agencyName"),closeAgency:$("#closeAgency"),cancelAgency:$("#cancelAgency"),nameDialog:$("#nameDialog"),nameForm:$("#nameForm"),displayName:$("#displayName"),toast:$("#toast")};
let currentUser=null,profile=null,allEvents=[],currentView="upcoming",selectedEvent=null,realtimeChannel=null,pendingEmail="",pendingAgencyEventId=null;
const esc=(v="")=>String(v).replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[m])),toDate=e=>new Date(`${e.event_date}T${e.event_time||"00:00"}:00`),isPast=e=>toDate(e)<new Date(),isCovered=e=>Boolean(e.driver_user_id||e.agency_covered);
function showToast(m){els.toast.textContent=m;els.toast.hidden=false;clearTimeout(showToast.t);showToast.t=setTimeout(()=>els.toast.hidden=true,2500)}
function formatDate(d){return new Intl.DateTimeFormat(undefined,{weekday:"short",month:"short",day:"numeric"}).format(new Date(`${d}T12:00:00`))}function formatTime(t){const[h,m]=(t||"00:00").split(":").map(Number);return new Intl.DateTimeFormat(undefined,{hour:"numeric",minute:"2-digit"}).format(new Date(2000,0,1,h,m))}
function agencyStatus(e){return e.agency_name?`✓ ${esc(e.agency_name)} is providing transportation`:`✓ Agency is covering transportation`}
function setView(v){currentView=v;$$('[data-view]').forEach(b=>b.classList.toggle("active",b.dataset.view===v));const m={upcoming:["Upcoming","Appointments and errands for Mimi and Grandaddy."],needs:["Needs Driver","Upcoming events that still need transportation."],mine:["My Rides","Transportation you have signed up to provide."],all:["All Events","Upcoming and past events."]};els.viewTitle.textContent=m[v][0];els.viewHelp.textContent=m[v][1];render()}
function visibleEvents(){const s=[...allEvents].sort((a,b)=>toDate(a)-toDate(b));if(currentView==="upcoming")return s.filter(e=>!isPast(e));if(currentView==="needs")return s.filter(e=>!isPast(e)&&!isCovered(e));if(currentView==="mine")return s.filter(e=>!isPast(e)&&e.driver_user_id===currentUser?.id);return s}
function cardHtml(e){const c=e.person==="Mimi"?"mimi":"grandaddy",st=e.agency_covered?`<strong class="covered">${agencyStatus(e)}</strong>`:e.driver_user_id?`<strong class="covered">✓ ${esc(e.driver_name||"Ride covered")} is driving</strong>`:`<strong class="needed-text">DRIVER NEEDED</strong>`,a=!isCovered(e)&&!isPast(e)?`<button type="button" data-claim="${e.id}">I can drive</button><button type="button" class="secondary" data-agency="${e.id}">Agency</button>`:"";return `<article class="card ${c}"><div class="top"><span class="person">${esc(e.person)}</span><span class="when">${formatDate(e.event_date)} · ${formatTime(e.event_time)}</span></div><h3>${esc(e.title)}</h3>${e.pickup_time?`<p class="location">🚗 Pickup / leave: ${formatTime(e.pickup_time)}</p>`:""}${e.location?`<p class="location">${esc(e.location)}</p>`:""}<div class="ride">${st}<div class="card-actions">${a}<button type="button" class="secondary" data-open="${e.id}">Details</button></div></div></article>`}
function render(){const n=allEvents.filter(e=>!isPast(e)&&!isCovered(e));els.needsBanner.hidden=!n.length;els.needsText.textContent=`${n.length} ${n.length===1?"ride needs":"rides need"} drivers`;const l=visibleEvents();els.events.innerHTML=l.map(cardHtml).join("");els.empty.hidden=!!l.length;$$('[data-open]').forEach(b=>b.onclick=()=>openDetails(b.dataset.open));$$('[data-claim]').forEach(b=>b.onclick=()=>claimRide(b.dataset.claim));$$('[data-agency]').forEach(b=>b.onclick=()=>openAgencyDialog(b.dataset.agency))}
async function loadEvents(){const{data,error}=await sb.from("events").select("*").order("event_date",{ascending:true}).order("event_time",{ascending:true});if(error)return showToast(error.message);allEvents=data||[];render()}function subscribeRealtime(){if(!realtimeChannel)realtimeChannel=sb.channel("events-changes").on("postgres_changes",{event:"*",schema:"public",table:"events"},loadEvents).subscribe()}
async function handleSession(s){if(!s){currentUser=null;profile=null;allEvents=[];els.login.hidden=false;els.app.hidden=true;if(realtimeChannel){await sb.removeChannel(realtimeChannel);realtimeChannel=null}return}currentUser=s.user;const email=(currentUser.email||"").trim().toLowerCase(),{data:allowed,error}=await sb.rpc("is_invited_email",{check_email:email});if(error||!allowed){await sb.auth.signOut();els.loginMsg.textContent="This email is not on the family access list.";return}profile={email,display_name:localStorage.getItem(`familyDisplayName:${email}`)||""};els.login.hidden=true;els.app.hidden=false;if(!profile.display_name)els.nameDialog.showModal();await loadEvents();subscribeRealtime()}
els.loginForm.onsubmit=async e=>{e.preventDefault();const email=els.email.value.trim().toLowerCase();els.loginMsg.textContent="Checking family access…";const{data:allowed,error:ie}=await sb.rpc("is_invited_email",{check_email:email});if(ie){els.loginMsg.textContent="Unable to check family access. Please try again.";return}if(!allowed){els.loginMsg.textContent="That email is not on the family access list.";return}els.loginMsg.textContent="Sending sign-in code…";const{error}=await sb.auth.signInWithOtp({email,options:{shouldCreateUser:true}});if(error){els.loginMsg.textContent=error.message;return}pendingEmail=email;els.loginForm.hidden=true;els.codeForm.hidden=false;els.loginMsg.textContent="Check your email for the sign-in code, then enter it here.";els.otpCode.focus()};
els.codeForm.onsubmit=async e=>{e.preventDefault();const token=els.otpCode.value.trim();els.loginMsg.textContent="Signing you in…";const{data,error}=await sb.auth.verifyOtp({email:pendingEmail,token,type:"email"});if(error){els.loginMsg.textContent=error.message;return}if(data.session)await handleSession(data.session)};els.changeEmailBtn.onclick=()=>{pendingEmail="";els.otpCode.value="";els.codeForm.hidden=true;els.loginForm.hidden=false;els.loginMsg.textContent=""};
els.signOut.onclick=()=>sb.auth.signOut();els.needsBanner.onclick=()=>setView("needs");$$('[data-view]').forEach(b=>b.onclick=()=>setView(b.dataset.view));
function openNewEvent(){els.eventHeading.textContent="Add Event";els.eventForm.reset();els.eventId.value="";els.person.value="Mimi";els.date.value=new Date().toISOString().slice(0,10);els.deleteBtn.hidden=true;els.eventDialog.showModal()}els.addBtn.onclick=openNewEvent;els.mobileAdd.onclick=openNewEvent;els.closeEvent.onclick=()=>els.eventDialog.close();els.cancelEvent.onclick=()=>els.eventDialog.close();
els.eventForm.onsubmit=async e=>{e.preventDefault();const p={person:els.person.value,title:els.title.value.trim(),event_date:els.date.value,event_time:els.time.value,pickup_time:els.pickupTime.value||null,location:els.location.value.trim()||null,notes:els.notes.value.trim()||null,updated_at:new Date().toISOString()},r=els.eventId.value?await sb.from("events").update(p).eq("id",els.eventId.value):await sb.from("events").insert({...p,created_by:currentUser.id,agency_covered:false,agency_name:null});if(r.error)return showToast(r.error.message);els.eventDialog.close();showToast("Saved.");await loadEvents()};
async function openDetails(id){selectedEvent=allEvents.find(e=>e.id===id);if(!selectedEvent)return;els.detailPerson.textContent=selectedEvent.person;els.detailTitle.textContent=selectedEvent.title;els.detailBody.innerHTML=`<p>📅 ${formatDate(selectedEvent.event_date)}</p><p>🕐 Appointment: ${formatTime(selectedEvent.event_time)}</p>${selectedEvent.pickup_time?`<p>🚗 Pickup / leave: ${formatTime(selectedEvent.pickup_time)}</p>`:""}${selectedEvent.location?`<p>📍 ${esc(selectedEvent.location)}</p>`:""}${selectedEvent.notes?`<p>📝 ${esc(selectedEvent.notes)}</p>`:""}`;if(selectedEvent.agency_covered){els.driverBox.innerHTML=`<p><strong>${agencyStatus(selectedEvent)}</strong></p><button id="removeAgencyBtn" type="button" class="secondary">Agency is no longer covering this ride</button>`;$("#removeAgencyBtn").onclick=()=>unmarkAgency(selectedEvent.id)}else if(selectedEvent.driver_user_id){const mine=selectedEvent.driver_user_id===currentUser.id;els.driverBox.innerHTML=`<p><strong>✓ ${esc(selectedEvent.driver_name||"Someone")} is driving</strong></p>${mine?'<button id="unclaimBtn" type="button" class="secondary">I can\'t drive anymore</button>':""}`;if(mine)$("#unclaimBtn").onclick=()=>unclaimRide(selectedEvent.id)}else{els.driverBox.innerHTML=`<p><strong>DRIVER NEEDED</strong></p>${!isPast(selectedEvent)?'<button id="claimDetailBtn" type="button">I can drive</button><button id="agencyDetailBtn" type="button" class="secondary">Agency</button>':""}`;if(!isPast(selectedEvent)){$("#claimDetailBtn").onclick=()=>claimRide(selectedEvent.id);$("#agencyDetailBtn").onclick=()=>openAgencyDialog(selectedEvent.id)}}els.detailDialog.showModal()}els.closeDetail.onclick=()=>els.detailDialog.close();
async function claimRide(id){if(!profile?.display_name){els.nameDialog.showModal();return}const{data,error}=await sb.from("events").update({driver_user_id:currentUser.id,driver_name:profile.display_name,agency_covered:false,agency_name:null,updated_at:new Date().toISOString()}).eq("id",id).is("driver_user_id",null).eq("agency_covered",false).select().maybeSingle();if(error)return showToast(error.message);if(!data)return showToast("This ride was just covered by someone else.");els.detailDialog.close();showToast("Thank you!");await loadEvents()}async function unclaimRide(id){const{error}=await sb.from("events").update({driver_user_id:null,driver_name:null,updated_at:new Date().toISOString()}).eq("id",id).eq("driver_user_id",currentUser.id);if(error)return showToast(error.message);els.detailDialog.close();showToast("Ride released.");await loadEvents()}
function openAgencyDialog(id){pendingAgencyEventId=id;els.agencyName.value="";if(els.detailDialog.open)els.detailDialog.close();els.agencyDialog.showModal();els.agencyName.focus()}
els.closeAgency.onclick=()=>{pendingAgencyEventId=null;els.agencyDialog.close()};els.cancelAgency.onclick=()=>{pendingAgencyEventId=null;els.agencyDialog.close()};
els.agencyForm.onsubmit=async e=>{e.preventDefault();if(!pendingAgencyEventId)return;const id=pendingAgencyEventId,name=els.agencyName.value.trim()||null;const{data,error}=await sb.from("events").update({agency_covered:true,agency_name:name,driver_user_id:null,driver_name:null,updated_at:new Date().toISOString()}).eq("id",id).is("driver_user_id",null).eq("agency_covered",false).select().maybeSingle();if(error)return showToast(error.message);if(!data)return showToast("This ride was just covered by someone else.");pendingAgencyEventId=null;els.agencyDialog.close();showToast("Agency transportation noted.");await loadEvents()};
async function unmarkAgency(id){const{error}=await sb.from("events").update({agency_covered:false,agency_name:null,updated_at:new Date().toISOString()}).eq("id",id).eq("agency_covered",true);if(error)return showToast(error.message);els.detailDialog.close();showToast("Agency coverage removed.");await loadEvents()}
els.editBtn.onclick=()=>{if(!selectedEvent)return;els.detailDialog.close();els.eventHeading.textContent="Edit Event";els.eventId.value=selectedEvent.id;els.person.value=selectedEvent.person;els.title.value=selectedEvent.title;els.date.value=selectedEvent.event_date;els.time.value=(selectedEvent.event_time||"").slice(0,5);els.pickupTime.value=(selectedEvent.pickup_time||"").slice(0,5);els.location.value=selectedEvent.location||"";els.notes.value=selectedEvent.notes||"";els.deleteBtn.hidden=false;els.eventDialog.showModal()};els.deleteBtn.onclick=async()=>{if(!els.eventId.value||!confirm("Delete this event?"))return;const{error}=await sb.from("events").delete().eq("id",els.eventId.value);if(error)return showToast(error.message);els.eventDialog.close();showToast("Deleted.");await loadEvents()};els.nameForm.onsubmit=e=>{e.preventDefault();const n=els.displayName.value.trim();if(!n)return;profile.display_name=n;localStorage.setItem(`familyDisplayName:${profile.email}`,n);els.nameDialog.close();showToast("Saved.")};
els.calendarBtn.onclick=()=>{if(!selectedEvent)return;const start=`${selectedEvent.event_date.replaceAll("-","")}T${(selectedEvent.event_time||"00:00").replace(":","")}00`,ed=new Date(toDate(selectedEvent).getTime()+3600000),p=n=>String(n).padStart(2,"0"),end=`${ed.getFullYear()}${p(ed.getMonth()+1)}${p(ed.getDate())}T${p(ed.getHours())}${p(ed.getMinutes())}00`,extra=selectedEvent.pickup_time?`Pickup / leave: ${formatTime(selectedEvent.pickup_time)}\\n`:"",body=["BEGIN:VCALENDAR","VERSION:2.0","PRODID:-//Family Transportation//EN","BEGIN:VEVENT",`DTSTART:${start}`,`DTEND:${end}`,`SUMMARY:${selectedEvent.person}: ${selectedEvent.title}`,`LOCATION:${selectedEvent.location||""}`,`DESCRIPTION:${extra}${(selectedEvent.notes||"").replace(/\n/g,"\\n")}`,"END:VEVENT","END:VCALENDAR"].join("\r\n"),a=document.createElement("a");a.href=URL.createObjectURL(new Blob([body],{type:"text/calendar"}));a.download=`${selectedEvent.person}-${selectedEvent.event_date}.ics`;a.click();URL.revokeObjectURL(a.href)};
const{data}=await sb.auth.getSession();await handleSession(data.session);sb.auth.onAuthStateChange(async(_e,s)=>handleSession(s));
